-- Supabase Database Schema for Brew & Bloom

-- 1. Create menu_items table
CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL,
    image TEXT NOT NULL,
    description TEXT NOT NULL,
    rating NUMERIC NOT NULL,
    badge TEXT
);

-- Insert initial menu data
INSERT INTO menu_items (id, title, category, price, image, description, rating, badge) VALUES
(1, 'Classic Latte', 'hot-brews', 150, 'assets/specialty_latte_art.png', 'Double shot of premium espresso with silky steamed milk and signature latte art.', 4.8, 'Bestseller'),
(2, 'Espresso Doppio', 'hot-brews', 120, 'assets/specialty_latte_art.png', 'Intense, aromatic double shot of custom-roasted Arabica beans.', 4.6, 'Classic'),
(3, 'Hazelnut Cappuccino', 'hot-brews', 160, 'assets/specialty_latte_art.png', 'Silky foam and rich espresso infused with warm, toasted hazelnut syrup.', 4.7, 'Popular'),
(4, 'Coffee on the Rocks', 'cold-brews', 170, 'assets/specialty_latte_art.png', 'Artisanal cold brew poured slowly over crystal-clear carved ice blocks.', 4.9, 'Specialty'),
(5, 'Caramel Frappe', 'cold-brews', 190, 'assets/specialty_latte_art.png', 'Blended cold coffee topped with whipped cream and a rich, buttery caramel drizzle.', 4.7, 'Sweet Touch'),
(6, 'Peri Peri Paneer Burger', 'fast-food', 180, 'assets/peri_peri_paneer_burger.png', 'Crispy grilled paneer patty with fresh crunch, melted cheddar, and fiery house peri peri sauce.', 4.9, 'Trending'),
(7, 'Veg Club Sandwich', 'fast-food', 140, 'assets/peri_peri_paneer_burger.png', 'Three layers of toasted sourdough loaded with fresh vegetables, premium cheese, and herb spread.', 4.5, 'Snack'),
(8, 'Alfredo Pasta', 'fast-food', 210, 'assets/peri_peri_paneer_burger.png', 'Penne tossed in a rich, velvety parmesan white sauce with garlic, mushrooms, and herbs.', 4.6, 'Premium'),
(9, 'Nutella Waffle', 'desserts', 160, 'assets/belgian_waffle_berries.png', 'Freshly baked crispy Belgian waffle topped generously with warm Nutella and fresh berries.', 4.9, 'Signature'),
(10, 'Blueberry Cheesecake Slice', 'desserts', 180, 'assets/belgian_waffle_berries.png', 'Creamy, rich New York-style cheesecake layered with sweet, tart blueberry compote.', 4.8, 'Chef Special'),
(11, 'Red Velvet Smoothie', 'refreshers', 170, 'assets/belgian_waffle_berries.png', 'Luxurious blend of vanilla cocoa, sweet strawberries, cream, and red velvet crumbles.', 4.7, 'Sweet Touch'),
(12, 'Mint Lime Mojito', 'refreshers', 130, 'assets/specialty_latte_art.png', 'Chilled sparkling soda muddled with fresh mint leaves, zesty key lime, and raw cane sugar.', 4.5, 'Refreshing')
ON CONFLICT (id) DO NOTHING;

-- 2. Create reservations table
CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    guests INTEGER NOT NULL,
    reservation_date DATE NOT NULL,
    reservation_time TEXT NOT NULL,
    table_number TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) but allow anonymous access for now (since we don't have auth setup)
-- Note: In a production app, you should add proper authentication and RLS policies.
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to menu_items" ON menu_items FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to reservations" ON reservations FOR INSERT WITH CHECK (true);
